### ISSUE TITLE
Typo in GitHub description

### ISSUE THREAD

**Issue by peterpeterparker** [byrdsandbytes/capacitor-contacts-plugin#1]
Hi,

Just noticed that you've got a typo in your GitHub description:

"A native Capcitor plugin to manage phone contacts on iOS/Android."

Unfortunately can send a PR to change this ;)

Best
David

**Comment by Idrimi** [comment]
Hi David,

thanks for the hint. Especially when it comes form Zürich. ;) Changed it. 

Greetings from Bern,

Johnny

**Comment by peterpeterparker** [comment]
Awesome @Idrimi 👍 

P.S.: If you ever happen to pass by Zürich and are in the mood to present something at our [Ionic Meetup Zürich](https://www.meetup.com/fr-FR/Ionic-Zurich/), like "How to create a cool Capacitor plugin", ping me! Soon we will be able to organize something IRL again ;)
