### ISSUE TITLE
Fetching contacts time to high, 20+segs

### ISSUE THREAD

**Issue by josewbr** [byrdsandbytes/capacitor-contacts-plugin#6]
Is it possible to speed up the process of fetching the device contacts? On android the demo app is taking 20+segs to fetch the contacts.

Thanks,

Jose

**Comment by Idrimi** [comment]
HI Jose,

i will have a look at it. It depends on how much contacts you have. How much contacts are you fetching?

**Comment by Idrimi** [comment]
Hi @josewbr,

just published a new version (0.0.2) here: https://github.com/capacitor-community/contacts and here: https://www.npmjs.com/package/@capacitor-community/contacts

The new release addresses the performance issues on android. You can just exchange the plugin without having to change the syntax on the js side. (I will probably be maintaining the plugin there and deprecating this repo)

**Comment by josewbr** [comment]
The performance is great now.. Thanks..

**Comment by Idrimi** [comment]
You're welcome, thx goes to a PR from a contributor.
